remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jca_v2_0]
description: [Eclipse Technology Compatibility Kit User's Guide for Jakarta EE Connector 2.0 for
                Technology
                Licensees, Release 2.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/jakartaee-tck
  download: https://jakarta.ee/specifications/connectors/2.0/
  #mailinglist: https://javaee.groups.io/g/tck_jca_v1_7
  #javadocs:
  docs: https://jakarta.ee/specifications/connectors/2.0/apidocs/
  #faq:

