remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jsp_v3_0]
description: [Oracle Technology Compatibility Kit User's Guide for Jakarta Server Pages 3.0 for Technology Licensees,
              Release 3.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/jakartaee-tck
  download: https://jakarta.ee/specifications/pages/3.0/
  #mailinglist: https://javaee.groups.io/g/tck_jsp_v2_3
  #javadocs:
  docs: https://jakarta.ee/specifications/pages/3.0/apidocs
  #faq:

