remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jta_v2_0]
description: [Oracle Technology Compatibility Kit User's Guide for Jakarta Transactions 2.0 for Technology
                Licensees,
              Release 2.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/jakartaee-tck
  download: https://jakarta.ee/specifications/transactions/2.0/
  #mailinglist: https://javaee.groups.io/g/tck_jta_v1_2
  #javadocs:
  docs: https://jakarta.ee/specifications/transactions/2.0/apidocs
  #faq:

